version: "3.9"
services:
  frontend:
    build:
      context: ./react-docker-sample/
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - './react-docker-sample:/app'
      - '/app/node_modules'
    networks:
      rede1:
  backend:
    build: ./express-docker-sample/
    ports:
      - 8000:8080
    volumes:
      - './express-docker-sample:/app'
      - '/app/node_modules'
    networks:
      rede1:
  backend2:
    build: ./express-axios-test/
    ports:
      - 8001:8081
    volumes:
      - './express-axios-test:/app'
      - '/app/node_modules'
    networks:
      rede1:
networks:
  rede1:
    driver: bridge
